config/routes.rb
Rails.application.routes.draw do
  # deviseGemのファイル作成を行うと自動で記述される
  devise_for :users
  # オリジナルURL（＋でパスがつかない）でもtweetsコントローラーのindexアクションが表示される
  root to:"tweets#index"
  # resourcesの書き方だとHTTPメソッドとURIは略される
  resources :tweets do
    resources :comments, only: :create
    # 7つのアクション以外ではuriにidを付与するかどうかをcollction(id非付与)かmember(id付与)で指定する
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション設定
  belongs_to :user
  belongs_to :tweet

  validates :text,presence:true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # バリデーション　textが空だと保存できない設定を決定
  # 保存はされないがcreateアクションは実行されるため、送信ボタンを押すとエラー等はなくtopページに戻る
  validates :text,presence:true
  # 1:1の関係でuserテーブルと繋がっていることを記述
  # テーブルにuser_idカラムが埋められてないと保存しないという設定も含まれている
  belongs_to :user
  has_many :comments
  # 検索結果表示
  # 引数には入力された検索キーワード
  def self.search(search)
    if search != ""
      # whereで条件に一致するものを検索
      # LIKEで部分一致検索を可能にしている
      # %は何かしらの文字列_は何かしらの一文字を表す
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # メールアドレスやパスワードの基本バリデーション設定
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #1対複数でtweetテーブルと繋がっていることを記述  
  has_many:tweets
  has_many:comments
  # 未入力だとテーブルへ登録できない＆6文字以内出ないとテーブルへ登録できないバリデーション
  validates :nickname,presence:true, length:{maximum:6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_actionで下層にある各コントローラーに対して事前に行うアクションであることを明記　if::コントローラー名?で設定されたコントローラーのときのみ実行することを記載
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  # deviseへ新たに追加するメソッドをconfigure_permitted_parametersというメソッドで作ることが慣習
  def configure_permitted_parameters
    # deviseの受け取れるパラメーターの宣言に新しいパラメーターを追加するメソッド
    # 第一引数にサインインサインアップアカウント情報の更新のどれかを記載　第三引数に追加したいカラム名のキーを記述する
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    # tweetのshowへ遷移
    # redirect_to "/tweets/#{comment.tweet.id}"
    redirect_to "/tweets/#{comment.tweet.id}" 
  end
  private
  def comment_params
    # permitはフォームで入力された情報のみのためtextのみです。
    # paramsのtweet_idには送付元詳細ページのuriパターンの中のtweet_idに当てはまる数字が入っている（ツイートテーブルのidがそこには入る設定）
    params.require(:comment).permit(:text).merge(user_id: current_user.id,tweet_id:params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # 優先的にメソッドの実行　exceptには実行しない　それ以外へ実行
  # ログインしてなかったら利用できないと言うメソッド
  before_action :move_to_index, except:[:index,:show,:search]

  # トップページ
  def index
    # インスタンス変数= テーブル名(大文字).all .allですべてのレコードを取得
    # @tweets = Tweet.all
    # N＋１問題の対策としてツイートテーブルと合わせてユーザーテーブルも事前に変数へ代入
    # oraderでcreted_at(作成日時)が降順の並び順で変数に代入される
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end
  # 新規投稿ページです。
  def new
    @tweet = Tweet.new
  end
  # 新規投稿のレスポンス対応でデータ追加
  def create
    # tweet_paramsで追加データをparamsの中から限定
    @tweet = Tweet.create(tweet_params)
    if @tweet.valid? #valid?によって、@tweetが正しく保存されるものなのかどうかを判断している。保存されるようであれば保存しルートパスへ。保存できないものであれば、新規投稿ページに戻っている
      @tweet.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  # 削除のレスポンス対応
  def destroy
    # find（特定idのみ取得メソッド）の後に送られてきたレコードの中からidを引き出して引数として入れることで削除したいツイートのみをtweet変数に代入
    tweet = Tweet.find(params[:id])
    # テーブルを削除
    tweet.destroy
    # 処理後ootに遷移
    redirect_to root_path
  end
  # アップデート編集ページ
  def edit
    set_tweet
  end
  # アップデートのレスポンス対応データ更新
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
    if tweet.valid? #valid?によって、@tweetが正しく保存されるものなのかどうかを判断している。保存されるようであれば保存しルートパスへ。保存できないものであれば、新規投稿ページに戻っている
      redirect_to root_path
    else
      render 'new'
    end
  end
  # 詳細ページ
  def show
    set_tweet
    # フォーム入力欄へ渡す空レコード
    @comment = Comment.new
    # コメント一覧に渡すコメントテーブル一覧（includesでN＋①問題対応でuserテーブル読み込み）
    # includesを使用するため.all省略
    @comments = @tweet.comments.includes(:user)

  end
  def search
    # モデルのsearchメソッドで検索にかけるテーブル名.モデルで行うメソッド(モデルに引数として渡す引数)
    @tweets = Tweet.search(params[:keyword])
  end
  # プライベートの下に書いたインスタンスメソッドはクラス外で呼び出せない
  private
  def tweet_params
    # paramsハッシュは色んな情報が入っているため、取得する情報を限定するために、requireでフォーム記入欄の指定カラムと紐づけたモデル名を、permitではフォームの中の情報から更に必要な入力欄を絞るために、フォームで紐づけたカラム名を記載する
    # mergeで他データベースの値をテーブルへ追加するデータに含めることができる
    # current_userでログイン中のレコードを抽出
    params.require(:tweet).permit(:image,:text).merge(user_id: current_user.id)
  end
  def set_tweet
    @tweet = Tweet.find(params[:id])

  end
  # サインインしてなかったら指定したアクションにリダイレクト
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    # ログインユーザーのニックネーム
    @nickname = user.nickname
    # ログインユーザーのレコードと紐づいてる複数のツイートデータ
    @tweets = user.tweets.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_lists(tweets)
    # 変数を宣言
    html = ''
    tweets.each do |tweet|
      # renderを使うとすべてのデータを表示させられる
      html += render(partial: 'tweet',locals: { tweet: tweet })
    end
    # 文字化け対策＆html変数を返す
    return raw(html)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%# cssの接続 application.cssに繋がる %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <%# ログインしているつtrueログインしてないとfalseが表示される %>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%# ログインユーザーのニックネーム表示 %>
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", user_path(current_user.id) %>
                <%# link_toでは基本的にgetメソッドとなるため,ログアウトの際にはDeleteメソッドとなるように記述 %>
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
            </span>
            <%= link_to "投稿する", new_tweet_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%# yieldの中にすべてのアクションファイル記述内容が記載される viewsのメインデータ アクション名.html.erbがページごとの部分的HTML %>
    <%= yield %>
    <footer>
      <p>
        Copyright PicTweet 2023.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%# tweetは部分テンプレートから変数で送られてきた、Tweetテーブルの新規で作成された空のレコード %>
<%# modelには新規で作成された入力されたデータを格納するレコードと新規入力するレコードに格納したいidを持ったアソシエーションされた他テーブルのレコードを入力する %>
<%= form_with(model: tweet, local: true) do |form| %>
<%# カラム名とフォームの参考を記入 %>
  <%= form.text_field :image, placeholder: "Image Url" %>
  <%= form.text_area :text, placeholder: "text", rows: "10" %>
  <%= form.submit "SEND" %>
<%end%>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <%# image_tagでimgタグをRubyで使用　"arrow_top.png"でapp/assets/images配下の画像ファイルまたはpublic配下の画像ファイルを指定　publickは以下の場合はファイル名の前に/記載 %>
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <%# ログインされててかつログインユーザー＝ツイート作成者だったら %>
      <% if user_signed_in? && tweet.user_id == current_user.id %>
        <li>
          <%# link_toで削除ボタンを作成　tweets/レコード.カラム名でidをパラメーターとして設置することで削除したいレコードをdestroyアクションに送る dataからはHTTPをdeleteにする記載%>
          <%= link_to '削除', "/tweets/#{tweet.id}", data: { turbo_method: :delete } %>
        </li>
        <li>
          <%# パス(uri pattern)を変数化(prefix(各パスごとのprefixはターミナルでrails routasで検索可能))してパラメータを引数として渡すことで削除したいレコードをdestroyアクションに送る %>
          <%= link_to '編集', edit_tweet_path(tweet.id) %>
        </li>
      <% end %>
      <li>
        <%= link_to '詳細', tweet_path(tweet.id) %>
      </li>
    </ul>
  </div>
  <p><%= tweet.text %></p>
  <span class="name">      
    <%# ツイートレコードのユーザーidを持った人の個別ページへ %>
    <a href=users/<%=tweet.user_id%>>
      <span>投稿者</span>
      <%# ツイートレコードのユーザーidを持った人のニックネーム表示 %>
      <%=tweet.user.nickname%>
    </a>
  </span>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%# editコントローラーからは中身が入ったレコードのインスタンス変数が送られてきてるのでupdateに送られる %>
    <%# 部分テンプレートに遷移 %>
    <%= render partial:"form",locals:{tweet:@tweet}%>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row">
  <%# 検索フォーム %>
  <%# urlで %>
  <%# 検索結果画面を表示するuriのpathとhttpメソッドを記述 %>
  <%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
    <%# keywordキーに入力内容を入れてフォーム送信を行う %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
<%
=begin%>
  <% @tweets.each do |tweet| %>
    <%# partialでtweet部分テンプレートを呼び出し %>
    <%# localsで部分テンプレートにtweetという変数にtweetを代入して継承 %>
    <%= render partial:"tweet",locals:{tweet:tweet}%>
  <% end %>
<%
=end
%>
  <%# ヘルパーメソッド二内容記述 %>
  <%= tweet_lists(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%# newコントローラーからは空レコードのインスタンス変数が送られてきてるのでcreateに送られる %>
    <%# 部分テンプレートに遷移 %>
    <%= render partial:"form",locals:{tweet: @tweet}%>
  </div>
</div>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
    <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
      <%# ログインされててかつログインユーザー＝ツイート作成者だったら %>
      <% if user_signed_in? && @tweet.user_id == current_user.id %>
        <div class="more">
          <%# image_tagでimgタグをRubyで使用　"arrow_top.png"でapp/assets/images配下の画像ファイルまたはpublic配下の画像ファイルを指定　publickは以下の場合はファイル名の前に/記載 %>
          <span><%= image_tag 'arrow_top.png' %></span>
            <ul class="more_list">
              <li>
                <%# link_toで削除ボタンを作成　tweets/レコード.カラム名でidをパラメーターとして設置することで削除したいレコードをdestroyアクションに送る dataからはHTTPをdeleteにする記載%>
                <%= link_to '削除', "/tweets/#{@tweet.id}", data: { turbo_method: :delete } %>
              </li>
              <li>
                <%# パス(uri pattern)を変数化(prefix(各パスごとのprefixはターミナルでrails routasで検索可能))してパラメータを引数として渡すことで削除したいレコードをdestroyアクションに送る %>
                <%= link_to '編集', edit_tweet_path(@tweet.id) %>
              </li>
            </ul>
        </div>
      <% end %>
      <p><%= @tweet.text %></p>
      <span class="name">      
        <%# ツイートレコードのユーザーidを持った人の個別ページへ %>
        <a href=/users/<%=@tweet.user_id%>%>
          <span>投稿者</span>
          <%# ツイートレコードのユーザーidを持った人のニックネーム表示 %>
          <%=@tweet.user.nickname%>
        </a>
      </span>
    </div>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  
  <% @tweets.each do |tweet| %>
    <%# partialでtweetsフォルダのtweet部分テンプレートを呼び出し %>
    <%# localsで部分テンプレートにtweetという変数にtweetを代入して継承 %>
    <%= render partial:"tweets/tweet",locals:{tweet:tweet}%>
  <% end %>
</div>